version: '3.7'

services:
    ui:
        build: ./
        command: npm run dev
        volumes:
            - ./:/usr/src/app:cached
            - node_modules:/usr/src/app/node_modules:cached
        ports:
            - '3000:3000'
volumes:
    node_modules: {}
